version: '3'

services:
  blog-gdg-bangla:
    build: .cloud/docker
    image: laravel-blog-img
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/application:cached

  horizon:
    build: .cloud/docker
    image: laravel-blog-img
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-blog
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached


  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - blog-gdg-bangla

  redis:
    image: redis
    ports:
      - "6379:6379"
